openapi: 3.0.0
info:
  title: お家ハッカソンGottiesチーム
  description: お家ハッカソンGottiesチーム
  termsOfService: https://hackmd.io/VMBt036JRJu_gBM07U64ww
  version: 1.0.0
servers:
- url: http://localhost:8080/
  description: ローカルサーバ
paths:
  /articles:
    get:
      tags:
      - articles
      description: 記事一覧
      operationId: articlesGET
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
                x-content-type: application/json
      x-swagger-router-controller: Articles
    post:
      tags:
      - articles
      description: 新規記事作成
      operationId: articlesPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "201":
          description: ok
      x-swagger-router-controller: Articles
  /articles/{id}:
    get:
      tags:
      - articles
      description: 記事詳細
      operationId: articlesIdGET
      parameters:
      - name: id
        in: path
        description: articles ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: A single User model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
      x-swagger-router-controller: Articles
components:
  schemas:
    Article:
      required:
      - after
      - before
      - category_id
      - id
      - title
      - user_id
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        before:
          type: string
          format: byte
        after:
          type: string
          format: byte
        body:
          type: string
        user_id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        before: ""
        user_id: user_id
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        after: ""
        title: title
        body: body
        category:
          id: id
          title: title
    Category:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        title:
          type: string
      example:
        id: id
        title: title
    body:
      type: object
      properties:
        title:
          required:
          - title
          type: string
        before:
          required:
          - before
          type: string
          format: byte
        after:
          required:
          - after
          type: string
          format: byte
        body:
          required:
          - body
          type: string
        category_id:
          required:
          - category_id
          type: integer
        user_id:
          required:
          - user_id
          type: string
